[2024-10-16T01:05:00.696+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-10-16T01:00:00+00:00 [queued]>
[2024-10-16T01:05:00.699+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2024-10-16T01:00:00+00:00 [queued]>
[2024-10-16T01:05:00.699+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T01:05:00.699+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-10-16T01:05:00.700+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T01:05:00.705+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-10-16 01:00:00+00:00
[2024-10-16T01:05:00.707+0000] {standard_task_runner.py:55} INFO - Started process 537 to run task
[2024-10-16T01:05:00.708+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2024-10-16T01:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpcj99i9a7']
[2024-10-16T01:05:00.709+0000] {standard_task_runner.py:83} INFO - Job 93: Subtask create_table
[2024-10-16T01:05:00.732+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2024-10-16T01:00:00+00:00 [running]> on host dcdd4c71b617
[2024-10-16T01:05:00.757+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-10-16T01:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-16T01:00:00+00:00
[2024-10-16T01:05:00.760+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-10-16T01:05:00.761+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2024-10-16T01:05:00.761+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-10-16T01:05:00.764+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20241016T010000, start_date=20241016T010500, end_date=20241016T010500
[2024-10-16T01:05:00.805+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-10-16T01:05:00.818+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
